### ISSUE TITLE
4-10 教材一个bug

### ISSUE THREAD

**Issue by blackdust** [blackdust/depot1#12]
我可以肯定的是 这肯定是教材的一个bug 因为周剑斌和我按照教材做的在加载样式表的时候从来都没成功过，都是只有基础的html页面 ，但是我有一次调试的时候报错了 使我产生了研究这个bug的想法
<img src='http://img.teamkn.com/i/hXQRnuNV.png' />

**Comment by blackdust** [comment]
我layout是按照教材的写法写的 
<img src='http://img.teamkn.com/i/cQ6OVKM2.png' />

**Comment by blackdust** [comment]
这是按照我的想法改成 ：all 才正常 可是教材上写得是 scaffold 这一行可以参照第一个图的错误位置 ，
我想问的是 那错误提示想让我干嘛？ 我按照这个提示在目录文件下写入了 他的要求 还是不成功才不得已使用这个方法的。这个错误是怎么产生的？

**Comment by fushang318** [comment]
1 标准写法是

首先写入
layout

```
<% = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
```

然后在 assets/applicaiton.css 中写入

![](http://img.teamkn.com/i/z1jxl74J.png)
