### ISSUE TITLE
教材做到了后面浏览器里的localhost/product 竟然不能访问。。。

### ISSUE THREAD

**Issue by blackdust** [blackdust/depot1#13]
以前是这样的。。。。
<img src='http://img.teamkn.com/i/gmk1QIwn.png' />

**Comment by blackdust** [comment]
做到后面了 这个都显示了 <img src='http://img.teamkn.com/i/iwolzutI.png' />

**Comment by blackdust** [comment]
但是浏览器内访问/products  成了这样。。。。。
<img src='http://img.teamkn.com/i/fACm7OE1.png' />

**Comment by fushang318** [comment]
在 application.html.erb 文件顶部加入

```
<% @cart = current_cart if @cart.blank? %>
```
