### ISSUE TITLE
本地修改错误了 想从github上远程覆盖掉

### ISSUE THREAD

**Issue by blackdust** [blackdust/depot1#3]
本地对rails内部文件操作错误不想弄了 想把远程仓库里的文件给传下来覆盖了 
已经证实的是
git pull（无效 显示 already-up-to-date）
git fetch （无效）

唯一能做的就是gitclone到另一个地方处理了

git pull 具体该怎么用呢？ 不是把远程仓库代码更新到本地吗？
 git fetch：相当于是从远程获取最新版本到本地，不会自动merge      git pull：是会merge的

**Comment by blackdust** [comment]
没有 commit  git checkout .

**Comment by blackdust** [comment]
已经commit了 使用git clone

**Comment by blackdust** [comment]
git pull 是指远程有更新 来把远程的更新 调整到本地 但是本地的修改属于本地的更新。。

**Comment by ben7th** [comment]
解决方法：

如果还没有 commit 的话，可以用

```
git checkout .
```

这样将使所有代码还原到最后一次 commit 的状态

如果已经 commit 了，最简单的方法就是，删除当前的工程（注意保存有用的代码到别的地方）
然后使用

```
git clone https:// ....
```

重新 clone 远程工程到本地

---

git pull 的意思并不是覆盖，而是和远程做一次比对，如果远程代码比本地的新，就把本地代码调整到远程代码最后一次 commit 的状态。而针对问题中的情况，本地代码比远程的新，所以 git pull 不会有任何作用。

**Comment by mimimhmh** [comment]
https://stackoverflow.com/questions/2007662/rollback-to-an-old-git-commit-in-a-public-repo
