### ISSUE TITLE
destroy这个方法并不是定义的而是隶属于某个类的 

### ISSUE THREAD

**Issue by blackdust** [blackdust/depot1#5]
<img src='http://img.teamkn.com/i/JXMcRSJo.png' />

**Comment by blackdust** [comment]
destroy 删除的商品项目是表里的吗？

**Comment by ben7th** [comment]
这里是翻译失误，其实他想表达的意思是：

点击按钮后，会请求 LineItemsController 中的 destroy 这个 action

所以，需要在 LineItemsController 中 定义一个 destroy 方法（也就是所谓的 action）
这个方法内部实现的逻辑是，从数据库删除一条记录，并且重定向页面

然后使得点击按钮时可以访问到这个方法，这样就可以做到通过点击按钮来删除一条记录了。
