### ISSUE TITLE
这一块希望说详细一点

### ISSUE THREAD

**Issue by blackdust** [blackdust/depot1#6]
<img src='http://img.teamkn.com/i/G8COIEy7.png' />

**Comment by blackdust** [comment]
find by 返回找到的product 通过product id 来找 我在想下面一段的作用和功能，为什么不line items 。find

**Comment by fushang318** [comment]
rails 4 推荐写法是

``` ruby
line_items.where(:product_id => product_id).first
```

**Comment by blackdust** [comment]
已经解决 ：通过在line items 里的 非主键（主键用find）来查找
