### ISSUE TITLE
button to

### ISSUE THREAD

**Issue by blackdust** [blackdust/depot1#7]
<img src='http://img.teamkn.com/i/ESMrIxhZ.png' />

**Comment by blackdust** [comment]
我只是想知道 button to 后面跟的是路径  后面的意思是指把index里的 product id 传递到 line items path里吗  line litems path 像是脚手架 line ltems的路径 具体传送到哪里？ line items里product变量被赋值了？

**Comment by ben7th** [comment]
首先，因为 routes.rb 里做了资源声明

``` ruby
resources :line_items
```

所以 rails 框架会动态生成一个名为 line_items_path 的方法

调用此方法，并不传任何参数时，会返回 `/line_items` 这个路径的字符串

而如果传参的话，比如像图中这样，传 line_items_path(:product_id => product)

则会返回

```
/line_items?product_id=xxx
```

这样的字符串，其中 xxx 就代表传给这个方法的 prodcut 对象的 id

**Comment by fushang318** [comment]
![](http://img.teamkn.com/i/qGjNb4mu.png)

user_active_tasks_path(:user_id => user_id)
