### ISSUE TITLE
给点提示。。

### ISSUE THREAD

**Issue by blackdust** [blackdust/depot1#9]
<img src='http://img.teamkn.com/i/AuCDcVNY.png' />

**Comment by ben7th** [comment]
这里的意思是，可以创建一个图片链接，来对指定路径发起 post 请求，以访问 create 方法

可以用以下的代码做到（好久没写 erb 了，可能有些不准确，大致就是这个意思）

``` haml
<%= link_to "create 方法对应的访问路径" , :method => :post do %>
  <img src='xxxxx'>
<% end %>
```
